apiVersion: core.napptive.com/v1alpha1
kind: ApplicationMetadata
name: "Nextcloud"
version: "latest"
description: A safe home for all your data. Access & share your files, calendars, contacts, mail & more from any device, on your terms.
keywords:
  - "nextcloud"
  - "sharing"
license: "Apache-2.0"
url: "https://nextcloud.com/"
doc: "https://docs.nextcloud.com/server/26/admin_manual/installation/index.html"
logo:
  - src: "https://i.pinimg.com/originals/dc/c3/ed/dcc3ed67e9eda31f1ff0a2a194cbba12.jpg"
    type: "image/jpg"
    size: "1250x830"

