apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nextcloud
  annotations:
    version: "latest"
    description: "A safe home for all your data. Access & share your files, calendars, contacts, mail & more from any device, on your terms."
spec:
  components:
    - name: nextcloud
      type: webservice
      properties:
        image: nextcloud:latest
        ports:
            - port: 80
              expose: true
        env:
          - name: NEXTCLOUD_ADMIN_USER
            value: "root"
          - name: NEXTCLOUD_ADMIN_PASSWORD
            value: "password"
        cpu: "200m"
        memory: "256Mi"
      traits:
        - type: napptive-ingress
          properties:
            name: nextcloud-server
            port: 80
            path: /
            rewritePath: /

